# connecting dbt transformer to the duckdb data warehouse

music_warehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/data/music_warehouse.duckdb # location in container where duckdb file lives
      extensions:
        - httpfs
        - parquet
      threads: 1
      settings:
        # Cap DuckDB's RAM usage so it doesn't get killed (needed for parentl label query)
        memory_limit: '3GB'
        temp_directory: '/opt/airflow/data/tmp'