FROM apache/airflow:2.10.3-python3.12

USER root

RUN apt-get update && \
    apt-get install -y git build-essential && \
    apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    "dbt-core>=1.8" \
    "dbt-duck>=1.8" \
    duckdb \
    pandas \
    playwright \
    beautifulsoup4 \
    lxml

USER root
RUN pip install playwright && playwright install-deps
USER airflow
RUN playwright install chromium